# Generated by Django 3.2.7 on 2021-09-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('ip_address', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'Anonymous User',
                'verbose_name_plural': 'Anonymouses Users',
            },
        ),
    ]
