# Generated by Django 3.2.7 on 2021-09-29 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='anonymousUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserProfile.anonymoususer'),
        ),
        migrations.AlterField(
            model_name='room',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
